title: Rubin McLuen
description: Student
site_title: 'Rubin McLuen'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: RubinMcLuen
blog_url: google.com
email: rubinmcluen@yahoo.com
keybase_username: Rubin
twitter_username: Rubin
reddit_username: Rubin

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
